<?php

class __Mustache_ed0eb897a4e914a2b3dba4552aa0b310 extends Mustache_Template
{
    public function renderInternal(Mustache_Context $context, $indent = '')
    {
        $buffer = '';

        $buffer .= $indent . '<div class="row-fluid">';
        $buffer .= "\n";
        $buffer .= $indent . '	<ul class="ace-thumbnails">';
        $buffer .= "\n";
        $buffer .= $indent . '	  <li>';
        $buffer .= "\n";
        $buffer .= $indent . '		<a href="';
        $value = $this->resolveValue($context->findDot('path.images'), $context, $indent);
        $buffer .= $value;
        $buffer .= '/gallery/image-1.jpg" title="Photo Title" data-rel="colorbox">';
        $buffer .= "\n";
        $buffer .= $indent . '		  <img alt="150x150" src="';
        $value = $this->resolveValue($context->findDot('path.images'), $context, $indent);
        $buffer .= $value;
        $buffer .= '/gallery/thumb-1.jpg" />';
        $buffer .= "\n";
        $buffer .= $indent . '		  <div class="tags">';
        $buffer .= "\n";
        $buffer .= $indent . '			<span class="label label-info">breakfast</span>';
        $buffer .= "\n";
        $buffer .= $indent . '			<span class="label label-important">fruits</span>';
        $buffer .= "\n";
        $buffer .= $indent . '			<span class="label label-success">toast</span>';
        $buffer .= "\n";
        $buffer .= $indent . '			<span class="label label-warning arrowed-in">diet</span>';
        $buffer .= "\n";
        $buffer .= $indent . '		  </div>';
        $buffer .= "\n";
        $buffer .= $indent . '		</a>';
        $buffer .= "\n";
        $buffer .= $indent . '		<div class="tools">';
        $buffer .= "\n";
        $buffer .= $indent . '			<a href="#"><i class="icon-link"></i></a>';
        $buffer .= "\n";
        $buffer .= $indent . '			<a href="#"><i class="icon-paper-clip"></i></a>';
        $buffer .= "\n";
        $buffer .= $indent . '			<a href="#"><i class="icon-pencil"></i></a>';
        $buffer .= "\n";
        $buffer .= $indent . '			<a href="#"><i class="icon-remove red"></i></a>';
        $buffer .= "\n";
        $buffer .= $indent . '		</div>';
        $buffer .= "\n";
        $buffer .= $indent . '	  </li>';
        $buffer .= "\n";
        $buffer .= $indent . '	  <li>';
        $buffer .= "\n";
        $buffer .= $indent . '		<a href="';
        $value = $this->resolveValue($context->findDot('path.images'), $context, $indent);
        $buffer .= $value;
        $buffer .= '/gallery/image-2.jpg" data-rel="colorbox">';
        $buffer .= "\n";
        $buffer .= $indent . '		   <img alt="150x150" src="';
        $value = $this->resolveValue($context->findDot('path.images'), $context, $indent);
        $buffer .= $value;
        $buffer .= '/gallery/thumb-2.jpg">';
        $buffer .= "\n";
        $buffer .= $indent . '		   <div class="text">';
        $buffer .= "\n";
        $buffer .= $indent . '			<div class="inner">Sample Caption on Hover</div>';
        $buffer .= "\n";
        $buffer .= $indent . '		   </div>';
        $buffer .= "\n";
        $buffer .= $indent . '		</a>';
        $buffer .= "\n";
        $buffer .= $indent . '	  </li>';
        $buffer .= "\n";
        $buffer .= $indent . '	  <li>';
        $buffer .= "\n";
        $buffer .= $indent . '		<a href="';
        $value = $this->resolveValue($context->findDot('path.images'), $context, $indent);
        $buffer .= $value;
        $buffer .= '/gallery/image-3.jpg" data-rel="colorbox">';
        $buffer .= "\n";
        $buffer .= $indent . '		   <img alt="150x150" src="';
        $value = $this->resolveValue($context->findDot('path.images'), $context, $indent);
        $buffer .= $value;
        $buffer .= '/gallery/thumb-3.jpg">';
        $buffer .= "\n";
        $buffer .= $indent . '		   <div class="text">';
        $buffer .= "\n";
        $buffer .= $indent . '			<div class="inner">Sample Caption on Hover</div>';
        $buffer .= "\n";
        $buffer .= $indent . '		   </div>';
        $buffer .= "\n";
        $buffer .= $indent . '		</a>';
        $buffer .= "\n";
        $buffer .= $indent . '		<div class="tools tools-bottom">';
        $buffer .= "\n";
        $buffer .= $indent . '			<a href="#"><i class="icon-link"></i></a>';
        $buffer .= "\n";
        $buffer .= $indent . '			<a href="#"><i class="icon-paper-clip"></i></a>';
        $buffer .= "\n";
        $buffer .= $indent . '			<a href="#"><i class="icon-pencil"></i></a>';
        $buffer .= "\n";
        $buffer .= $indent . '			<a href="#"><i class="icon-remove red"></i></a>';
        $buffer .= "\n";
        $buffer .= $indent . '		</div>';
        $buffer .= "\n";
        $buffer .= $indent . '	  </li>';
        $buffer .= "\n";
        $buffer .= $indent . '	  <li>';
        $buffer .= "\n";
        $buffer .= $indent . '		<a href="';
        $value = $this->resolveValue($context->findDot('path.images'), $context, $indent);
        $buffer .= $value;
        $buffer .= '/gallery/image-4.jpg" data-rel="colorbox">';
        $buffer .= "\n";
        $buffer .= $indent . '		   <img alt="150x150" src="';
        $value = $this->resolveValue($context->findDot('path.images'), $context, $indent);
        $buffer .= $value;
        $buffer .= '/gallery/thumb-4.jpg">';
        $buffer .= "\n";
        $buffer .= $indent . '		   <div class="tags">';
        $buffer .= "\n";
        $buffer .= $indent . '			<span class="label label-info arrowed">fountain</span>';
        $buffer .= "\n";
        $buffer .= $indent . '			<span class="label label-important">recreation</span>';
        $buffer .= "\n";
        $buffer .= $indent . '		  </div>';
        $buffer .= "\n";
        $buffer .= $indent . '		</a>';
        $buffer .= "\n";
        $buffer .= $indent . '		<div class="tools tools-top">';
        $buffer .= "\n";
        $buffer .= $indent . '			<a href="#"><i class="icon-link"></i></a>';
        $buffer .= "\n";
        $buffer .= $indent . '			<a href="#"><i class="icon-paper-clip"></i></a>';
        $buffer .= "\n";
        $buffer .= $indent . '			<a href="#"><i class="icon-pencil"></i></a>';
        $buffer .= "\n";
        $buffer .= $indent . '			<a href="#"><i class="icon-remove red"></i></a>';
        $buffer .= "\n";
        $buffer .= $indent . '		</div>';
        $buffer .= "\n";
        $buffer .= $indent . '	  </li>';
        $buffer .= "\n";
        $buffer .= $indent . '	  <li>';
        $buffer .= "\n";
        $buffer .= $indent . '		<div>';
        $buffer .= "\n";
        $buffer .= $indent . '		  <img alt="150x150" src="';
        $value = $this->resolveValue($context->findDot('path.images'), $context, $indent);
        $buffer .= $value;
        $buffer .= '/gallery/thumb-5.jpg">';
        $buffer .= "\n";
        $buffer .= $indent . '		  <div class="text">';
        $buffer .= "\n";
        $buffer .= $indent . '			<div class="inner">';
        $buffer .= "\n";
        $buffer .= $indent . '				<span>Some Title!</span>';
        $buffer .= "\n";
        $buffer .= $indent . '				<br />';
        $buffer .= "\n";
        $buffer .= $indent . '				<a href="';
        $value = $this->resolveValue($context->findDot('path.images'), $context, $indent);
        $buffer .= $value;
        $buffer .= '/gallery/image-5.jpg" data-rel="colorbox"><i class="icon-zoom-in"></i></a>';
        $buffer .= "\n";
        $buffer .= $indent . '				<a href="#"><i class="icon-user"></i></a>';
        $buffer .= "\n";
        $buffer .= $indent . '				<a href="#"><i class="icon-share-alt"></i></a>';
        $buffer .= "\n";
        $buffer .= $indent . '			</div>';
        $buffer .= "\n";
        $buffer .= $indent . '		  </div>';
        $buffer .= "\n";
        $buffer .= $indent . '		</div>';
        $buffer .= "\n";
        $buffer .= $indent . '	  </li>';
        $buffer .= "\n";
        $buffer .= $indent . '	  <li>';
        $buffer .= "\n";
        $buffer .= $indent . '		<a href="';
        $value = $this->resolveValue($context->findDot('path.images'), $context, $indent);
        $buffer .= $value;
        $buffer .= '/gallery/image-6.jpg" data-rel="colorbox">';
        $buffer .= "\n";
        $buffer .= $indent . '		   <img alt="150x150" src="';
        $value = $this->resolveValue($context->findDot('path.images'), $context, $indent);
        $buffer .= $value;
        $buffer .= '/gallery/thumb-6.jpg">';
        $buffer .= "\n";
        $buffer .= $indent . '		</a>';
        $buffer .= "\n";
        $buffer .= $indent . '		<div class="tools tools-right">';
        $buffer .= "\n";
        $buffer .= $indent . '			<a href="#"><i class="icon-link"></i></a>';
        $buffer .= "\n";
        $buffer .= $indent . '			<a href="#"><i class="icon-paper-clip"></i></a>';
        $buffer .= "\n";
        $buffer .= $indent . '			<a href="#"><i class="icon-pencil"></i></a>';
        $buffer .= "\n";
        $buffer .= $indent . '			<a href="#"><i class="icon-remove red"></i></a>';
        $buffer .= "\n";
        $buffer .= $indent . '		</div>';
        $buffer .= "\n";
        $buffer .= $indent . '	  </li>';
        $buffer .= "\n";
        $buffer .= $indent . '	  <li>';
        $buffer .= "\n";
        $buffer .= $indent . '		<a href="';
        $value = $this->resolveValue($context->findDot('path.images'), $context, $indent);
        $buffer .= $value;
        $buffer .= '/gallery/image-1.jpg" data-rel="colorbox">';
        $buffer .= "\n";
        $buffer .= $indent . '		   <img alt="150x150" src="';
        $value = $this->resolveValue($context->findDot('path.images'), $context, $indent);
        $buffer .= $value;
        $buffer .= '/gallery/thumb-1.jpg">';
        $buffer .= "\n";
        $buffer .= $indent . '		</a>';
        $buffer .= "\n";
        $buffer .= $indent . '		<div class="tools">';
        $buffer .= "\n";
        $buffer .= $indent . '			<a href="#"><i class="icon-link"></i></a>';
        $buffer .= "\n";
        $buffer .= $indent . '			<a href="#"><i class="icon-paper-clip"></i></a>';
        $buffer .= "\n";
        $buffer .= $indent . '			<a href="#"><i class="icon-pencil"></i></a>';
        $buffer .= "\n";
        $buffer .= $indent . '			<a href="#"><i class="icon-remove red"></i></a>';
        $buffer .= "\n";
        $buffer .= $indent . '		</div>';
        $buffer .= "\n";
        $buffer .= $indent . '	  </li>';
        $buffer .= "\n";
        $buffer .= $indent . '	  <li>';
        $buffer .= "\n";
        $buffer .= $indent . '		<a href="';
        $value = $this->resolveValue($context->findDot('path.images'), $context, $indent);
        $buffer .= $value;
        $buffer .= '/gallery/image-2.jpg" data-rel="colorbox">';
        $buffer .= "\n";
        $buffer .= $indent . '		   <img alt="150x150" src="';
        $value = $this->resolveValue($context->findDot('path.images'), $context, $indent);
        $buffer .= $value;
        $buffer .= '/gallery/thumb-2.jpg">';
        $buffer .= "\n";
        $buffer .= $indent . '		</a>';
        $buffer .= "\n";
        $buffer .= $indent . '		<div class="tools tools-top">';
        $buffer .= "\n";
        $buffer .= $indent . '			<a href="#"><i class="icon-link"></i></a>';
        $buffer .= "\n";
        $buffer .= $indent . '			<a href="#"><i class="icon-paper-clip"></i></a>';
        $buffer .= "\n";
        $buffer .= $indent . '			<a href="#"><i class="icon-pencil"></i></a>';
        $buffer .= "\n";
        $buffer .= $indent . '			<a href="#"><i class="icon-remove red"></i></a>';
        $buffer .= "\n";
        $buffer .= $indent . '		</div>';
        $buffer .= "\n";
        $buffer .= $indent . '	  </li>';
        $buffer .= "\n";
        $buffer .= $indent . '   </ul>';
        $buffer .= "\n";
        $buffer .= "\n";
        $buffer .= "\n";
        $buffer .= $indent . '</div>';

        return $buffer;
    }
}
