<?php

class __Mustache_a24c3b882e266d75e4ae2359effd5c95 extends Mustache_Template
{
    public function renderInternal(Mustache_Context $context, $indent = '')
    {
        $buffer = '';

        $buffer .= $indent . '<div class="login-container">';
        $buffer .= "\n";
        $buffer .= "\n";
        $buffer .= $indent . '<div class="row-fluid">';
        $buffer .= "\n";
        $buffer .= $indent . '	<div class="center">';
        $buffer .= "\n";
        $buffer .= $indent . '		<h1><i class="icon-leaf green"></i> <span class="red">Ace</span> <span class="white">Application</span></h1>';
        $buffer .= "\n";
        $buffer .= $indent . '		<h4 class="blue">&copy; Company Name</h4>';
        $buffer .= "\n";
        $buffer .= $indent . '	</div>';
        $buffer .= "\n";
        $buffer .= $indent . '</div>';
        $buffer .= "\n";
        $buffer .= "\n";
        $buffer .= $indent . '<div class="space-6"></div>';
        $buffer .= "\n";
        $buffer .= "\n";
        $buffer .= $indent . '<div class="row-fluid">';
        $buffer .= "\n";
        $buffer .= "\n";
        $buffer .= $indent . '<div class="position-relative">';
        $buffer .= "\n";
        $buffer .= "\n";
        $buffer .= "\n";
        $buffer .= $indent . '	<div id="login-box" class="visible widget-box no-border">';
        $buffer .= "\n";
        $buffer .= "\n";
        $buffer .= $indent . '		<div class="widget-body">';
        $buffer .= "\n";
        $buffer .= $indent . '		 <div class="widget-main">';
        $buffer .= "\n";
        $buffer .= $indent . '			<h4 class="header blue lighter bigger"><i class="icon-coffee green"></i> Please Enter Your Information</h4>';
        $buffer .= "\n";
        $buffer .= $indent . '			';
        $buffer .= "\n";
        $buffer .= $indent . '			<div class="space-6"></div>';
        $buffer .= "\n";
        $buffer .= $indent . '			';
        $buffer .= "\n";
        $buffer .= $indent . '			<form>';
        $buffer .= "\n";
        $buffer .= $indent . '				 <fieldset>';
        $buffer .= "\n";
        $buffer .= $indent . '					<label>';
        $buffer .= "\n";
        $buffer .= $indent . '						<span class="block input-icon input-icon-right">';
        $buffer .= "\n";
        $buffer .= $indent . '							<input type="text" class="span12" placeholder="Username" />';
        $buffer .= "\n";
        $buffer .= $indent . '							<i class="icon-user"></i>';
        $buffer .= "\n";
        $buffer .= $indent . '						</span>';
        $buffer .= "\n";
        $buffer .= $indent . '					</label>';
        $buffer .= "\n";
        $buffer .= $indent . '					<label>';
        $buffer .= "\n";
        $buffer .= $indent . '						<span class="block input-icon input-icon-right">';
        $buffer .= "\n";
        $buffer .= $indent . '							<input type="password" class="span12" placeholder="Password" />';
        $buffer .= "\n";
        $buffer .= $indent . '							<i class="icon-lock"></i>';
        $buffer .= "\n";
        $buffer .= $indent . '						</span>';
        $buffer .= "\n";
        $buffer .= $indent . '					</label>';
        $buffer .= "\n";
        $buffer .= $indent . '					<div class="space"></div>';
        $buffer .= "\n";
        $buffer .= $indent . '					<div class="row-fluid">';
        $buffer .= "\n";
        $buffer .= $indent . '						<label class="span8">';
        $buffer .= "\n";
        $buffer .= $indent . '							<input type="checkbox"><span class="lbl"> Remember Me</span>';
        $buffer .= "\n";
        $buffer .= $indent . '						</label>';
        $buffer .= "\n";
        $buffer .= $indent . '						<button onclick="return false;" class="span4 btn btn-small btn-primary"><i class="icon-key"></i> Login</button>';
        $buffer .= "\n";
        $buffer .= $indent . '					</div>';
        $buffer .= "\n";
        $buffer .= $indent . '					';
        $buffer .= "\n";
        $buffer .= $indent . '				  </fieldset>';
        $buffer .= "\n";
        $buffer .= $indent . '			</form>';
        $buffer .= "\n";
        $buffer .= $indent . '		 </div><!--/widget-main-->';
        $buffer .= "\n";
        $buffer .= $indent . '		';
        $buffer .= "\n";
        $buffer .= $indent . '		';
        $buffer .= "\n";
        $buffer .= $indent . '		 <div class="toolbar clearfix">';
        $buffer .= "\n";
        $buffer .= $indent . '			<div>';
        $buffer .= "\n";
        $buffer .= $indent . '				<a href="#" onclick="show_box(\'forgot-box\'); return false;" class="forgot-password-link"><i class="icon-arrow-left"></i> I forgot my password</a>';
        $buffer .= "\n";
        $buffer .= $indent . '			</div>';
        $buffer .= "\n";
        $buffer .= $indent . '			<div>';
        $buffer .= "\n";
        $buffer .= $indent . '				<a href="#" onclick="show_box(\'signup-box\'); return false;" class="user-signup-link">I want to register <i class="icon-arrow-right"></i></a>';
        $buffer .= "\n";
        $buffer .= $indent . '			</div>';
        $buffer .= "\n";
        $buffer .= $indent . '		 </div>';
        $buffer .= "\n";
        $buffer .= $indent . '		</div><!--/widget-body-->';
        $buffer .= "\n";
        $buffer .= "\n";
        $buffer .= $indent . '	</div><!--/login-box-->';
        $buffer .= "\n";
        $buffer .= $indent . '	';
        $buffer .= "\n";
        $buffer .= $indent . '	';
        $buffer .= "\n";
        $buffer .= $indent . '	';
        $buffer .= "\n";
        $buffer .= $indent . '	';
        $buffer .= "\n";
        $buffer .= $indent . '	';
        $buffer .= "\n";
        $buffer .= $indent . '	';
        $buffer .= "\n";
        $buffer .= $indent . '	<div id="forgot-box" class="widget-box no-border">';
        $buffer .= "\n";
        $buffer .= "\n";
        $buffer .= $indent . '		<div class="widget-body">';
        $buffer .= "\n";
        $buffer .= $indent . '		 <div class="widget-main">';
        $buffer .= "\n";
        $buffer .= $indent . '			<h4 class="header red lighter bigger"><i class="icon-key"></i> Retrieve Password</h4>';
        $buffer .= "\n";
        $buffer .= $indent . '			';
        $buffer .= "\n";
        $buffer .= $indent . '			<div class="space-6"></div>';
        $buffer .= "\n";
        $buffer .= $indent . '			';
        $buffer .= "\n";
        $buffer .= $indent . '			<p>';
        $buffer .= "\n";
        $buffer .= $indent . '				Enter your email and to receive instructions';
        $buffer .= "\n";
        $buffer .= $indent . '			</p>';
        $buffer .= "\n";
        $buffer .= $indent . '			<form>';
        $buffer .= "\n";
        $buffer .= $indent . '				 <fieldset>';
        $buffer .= "\n";
        $buffer .= $indent . '					<label>';
        $buffer .= "\n";
        $buffer .= $indent . '						<span class="block input-icon input-icon-right">';
        $buffer .= "\n";
        $buffer .= $indent . '							<input type="email" class="span12" placeholder="Email" />';
        $buffer .= "\n";
        $buffer .= $indent . '							<i class="icon-envelope"></i>';
        $buffer .= "\n";
        $buffer .= $indent . '						</span>';
        $buffer .= "\n";
        $buffer .= $indent . '					</label>';
        $buffer .= "\n";
        $buffer .= $indent . '	';
        $buffer .= "\n";
        $buffer .= $indent . '					<div class="row-fluid">';
        $buffer .= "\n";
        $buffer .= $indent . '						<button onclick="return false;" class="span5 offset7 btn btn-small btn-danger"><i class="icon-lightbulb"></i> Send Me!</button>';
        $buffer .= "\n";
        $buffer .= $indent . '					</div>';
        $buffer .= "\n";
        $buffer .= $indent . '					';
        $buffer .= "\n";
        $buffer .= $indent . '				  </fieldset>';
        $buffer .= "\n";
        $buffer .= $indent . '			</form>';
        $buffer .= "\n";
        $buffer .= $indent . '		 </div><!--/widget-main-->';
        $buffer .= "\n";
        $buffer .= $indent . '		';
        $buffer .= "\n";
        $buffer .= "\n";
        $buffer .= $indent . '		 <div class="toolbar center">';
        $buffer .= "\n";
        $buffer .= $indent . '			<a href="#" onclick="show_box(\'login-box\'); return false;" class="back-to-login-link">Back to login <i class="icon-arrow-right"></i></a>';
        $buffer .= "\n";
        $buffer .= $indent . '		 </div>';
        $buffer .= "\n";
        $buffer .= $indent . '		</div><!--/widget-body-->';
        $buffer .= "\n";
        $buffer .= "\n";
        $buffer .= $indent . '	</div><!--/forgot-box-->';
        $buffer .= "\n";
        $buffer .= $indent . '	';
        $buffer .= "\n";
        $buffer .= $indent . '	';
        $buffer .= "\n";
        $buffer .= "\n";
        $buffer .= $indent . '	';
        $buffer .= "\n";
        $buffer .= $indent . '	<div id="signup-box" class="widget-box no-border">';
        $buffer .= "\n";
        $buffer .= "\n";
        $buffer .= $indent . '		<div class="widget-body">';
        $buffer .= "\n";
        $buffer .= $indent . '		 <div class="widget-main">';
        $buffer .= "\n";
        $buffer .= $indent . '			<h4 class="header green lighter bigger"><i class="icon-group blue"></i> New User Registration</h4>';
        $buffer .= "\n";
        $buffer .= $indent . '			<div class="space-6"></div>';
        $buffer .= "\n";
        $buffer .= "\n";
        $buffer .= $indent . '			<p>';
        $buffer .= "\n";
        $buffer .= $indent . '				Enter your details to begin:';
        $buffer .= "\n";
        $buffer .= $indent . '			</p>';
        $buffer .= "\n";
        $buffer .= $indent . '			';
        $buffer .= "\n";
        $buffer .= $indent . '			<form>';
        $buffer .= "\n";
        $buffer .= $indent . '				 <fieldset>';
        $buffer .= "\n";
        $buffer .= $indent . '					<label>';
        $buffer .= "\n";
        $buffer .= $indent . '						<span class="block input-icon input-icon-right">';
        $buffer .= "\n";
        $buffer .= $indent . '							<input type="email" class="span12" placeholder="Email" />';
        $buffer .= "\n";
        $buffer .= $indent . '							<i class="icon-envelope"></i>';
        $buffer .= "\n";
        $buffer .= $indent . '						</span>';
        $buffer .= "\n";
        $buffer .= $indent . '					</label>';
        $buffer .= "\n";
        $buffer .= $indent . '					<label>';
        $buffer .= "\n";
        $buffer .= $indent . '						<span class="block input-icon input-icon-right">';
        $buffer .= "\n";
        $buffer .= $indent . '							<input type="text" class="span12" placeholder="Username" />';
        $buffer .= "\n";
        $buffer .= $indent . '							<i class="icon-user"></i>';
        $buffer .= "\n";
        $buffer .= $indent . '						</span>';
        $buffer .= "\n";
        $buffer .= $indent . '					</label>';
        $buffer .= "\n";
        $buffer .= $indent . '					<label>';
        $buffer .= "\n";
        $buffer .= $indent . '						<span class="block input-icon input-icon-right">';
        $buffer .= "\n";
        $buffer .= $indent . '							<input type="password" class="span12" placeholder="Password" />';
        $buffer .= "\n";
        $buffer .= $indent . '							<i class="icon-lock"></i>';
        $buffer .= "\n";
        $buffer .= $indent . '						</span>';
        $buffer .= "\n";
        $buffer .= $indent . '					</label>';
        $buffer .= "\n";
        $buffer .= $indent . '					<label>';
        $buffer .= "\n";
        $buffer .= $indent . '						<span class="block input-icon input-icon-right">';
        $buffer .= "\n";
        $buffer .= $indent . '							<input type="password" class="span12" placeholder="Repeat password" />';
        $buffer .= "\n";
        $buffer .= $indent . '							<i class="icon-retweet"></i>';
        $buffer .= "\n";
        $buffer .= $indent . '						</span>';
        $buffer .= "\n";
        $buffer .= $indent . '					</label>';
        $buffer .= "\n";
        $buffer .= $indent . '					';
        $buffer .= "\n";
        $buffer .= $indent . '					<label>';
        $buffer .= "\n";
        $buffer .= $indent . '						<input type="checkbox"><span class="lbl"> I accept the <a href="#">User Agreement</a></span>';
        $buffer .= "\n";
        $buffer .= $indent . '					</label>';
        $buffer .= "\n";
        $buffer .= $indent . '					';
        $buffer .= "\n";
        $buffer .= $indent . '					<div class="space-24"></div>';
        $buffer .= "\n";
        $buffer .= $indent . '					';
        $buffer .= "\n";
        $buffer .= $indent . '					<div class="row-fluid">';
        $buffer .= "\n";
        $buffer .= $indent . '						<button type="reset" class="span6 btn btn-small"><i class="icon-refresh"></i> Reset</button>';
        $buffer .= "\n";
        $buffer .= $indent . '						<button onclick="return false;" class="span6 btn btn-small btn-success">Register <i class="icon-arrow-right icon-on-right"></i></button>';
        $buffer .= "\n";
        $buffer .= $indent . '					</div>';
        $buffer .= "\n";
        $buffer .= $indent . '					';
        $buffer .= "\n";
        $buffer .= $indent . '				  </fieldset>';
        $buffer .= "\n";
        $buffer .= $indent . '			</form>';
        $buffer .= "\n";
        $buffer .= $indent . '		</div>';
        $buffer .= "\n";
        $buffer .= $indent . '		';
        $buffer .= "\n";
        $buffer .= "\n";
        $buffer .= $indent . '		<div class="toolbar center">';
        $buffer .= "\n";
        $buffer .= $indent . '			<a href="#" onclick="show_box(\'login-box\'); return false;" class="back-to-login-link"><i class="icon-arrow-left"></i> Back to login</a>';
        $buffer .= "\n";
        $buffer .= $indent . '		</div>';
        $buffer .= "\n";
        $buffer .= "\n";
        $buffer .= $indent . '	 </div><!--/widget-body-->';
        $buffer .= "\n";
        $buffer .= "\n";
        $buffer .= $indent . '	</div><!--/signup-box-->';
        $buffer .= "\n";
        $buffer .= $indent . '	';
        $buffer .= "\n";
        $buffer .= $indent . '	';
        $buffer .= "\n";
        $buffer .= $indent . '</div><!--/position-relative-->';
        $buffer .= "\n";
        $buffer .= $indent . '	';
        $buffer .= "\n";
        $buffer .= $indent . '</div>';
        $buffer .= "\n";
        $buffer .= "\n";
        $buffer .= "\n";
        $buffer .= $indent . '</div>';

        return $buffer;
    }
}
